// <auto-generated />
namespace MoviesRenting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202002140946562_editMovie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
